### ISSUE TITLE
The configs of BIFPN

### ISSUE THREAD

**Issue by lexiqi** [yoneken1/pytorch_bifpn_for_mmdetection#1]
![image](https://user-images.githubusercontent.com/25817952/79400291-61d0b800-7fb8-11ea-9c54-361b40644154.png)
hi, I want to make sure the configs of BIFPN is it right?? The result of BIFPN is not very well.

**Comment by yoneken1** [comment]
Please set the “stack” value (default is only 1 stack).
And my implementation is not correct. Please refer to original implementation.

**Comment by lexiqi** [comment]
> Please set the “stack” value (default is only 1 stack).
> And my implementation is not correct. Please refer to original implementation.

OK,3Q~~
